package math;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class Phrases {
    static final List<String> encouragingPhrasesList = new ArrayList<>(
            List.of("Great job!",
                    "Excellent!",
                    "Fantastic!",
                    "You nailed it!",
                    "Well done!",
                    "You're a superstar!",
                    "Brilliant!",
                    "Way to go!",
                    "Awesome work!",
                    "Outstanding!",
                    "You're on fire!",
                    "You're so smart!",
                    "Superb effort!",
                    "Terrific job!",
                    "Perfect answer!",
                    "Impressive!",
                    "You're on the right track!",
                    "Spot on!",
                    "You've got it!",
                    "Keep up the good work!",
                    "You're a genius!",
                    "Top-notch response!",
                    "Wow, that's correct!",
                    "Incredible job!",
                    "You make it look easy!",
                    "You're a whiz!",
                    "Phenomenal work!",
                    "That's the way to do it!",
                    "Exceptional effort!",
                    "You aced it!",
                    "You're amazing!",
                    "Bravo!",
                    "Excellent reasoning!",
                    "You're so clever!",
                    "Remarkable!",
                    "Perfectly done!",
                    "You're a problem-solving pro!",
                    "Outstanding performance!",
                    "You really know your stuff!",
                    "That's exactly right!",
                    "You've got the hang of it!",
                    "You're a quick learner!",
                    "Super job!",
                    "Great thinking!",
                    "Well played!",
                    "You're an absolute star!",
                    "Stellar response!",
                    "You're on fire today!",
                    "You're unstoppable!",
                    "Spotless answer!",
                    "You're a champion!",
                    "You're a natural!",
                    "I'm impressed!",
                    "Flawless work!",
                    "You've got the talent!",
                    "You're really getting it!",
                    "You're shining bright!",
                    "Bravo, my friend!",
                    "You're getting better and better!",
                    "You're making me proud!",
                    "You're on a roll!",
                    "You're a true scholar!",
                    "Perfect execution!",
                    "You're so resourceful!",
                    "You're a problem-solving genius!",
                    "That's the spirit!",
                    "You've got the skills!",
                    "You're a real pro!",
                    "You're a mastermind!",
                    "You're one sharp cookie!",
                    "Well-thought-out answer!",
                    "You're making leaps and bounds!",
                    "That's how it's done!",
                    "You're a whiz kid!",
                    "You've got the right idea!",
                    "You're a class act!",
                    "You're a quick thinker!",
                    "You're really on top of things!",
                    "You've got the magic touch!",
                    "You're a bright spark!",
                    "You're an inspiration!",
                    "You're a star student!",
                    "You're on the right path!",
                    "You're a genius in the making!",
                    "You're the best!",
                    "You're truly exceptional!",
                    "You're ahead of the game!",
                    "You're a future leader!",
                    "You're a real expert!",
                    "You're a shining example!",
                    "You've got a brilliant mind!",
                    "You're a problem-crushing machine!",
                    "You've got the gift of knowledge!",
                    "You're a smart cookie!",
                    "You're a shining star!",
                    "You've got what it takes!",
                    "You're a real talent!",
                    "You're making great strides!",
                    "You're a true gem!",
                    "You've got the right answer down pat!")
    );

    public static String getRandomEncouragingWord(){
        Random random = new Random();
        int randomIndex = random.nextInt(encouragingPhrasesList.size());
        return updateWithName(encouragingPhrasesList.get(randomIndex));
    }

    private static  String updateWithName(String word){
        word = word.replace("!", " Chriselda" + "!!!!!!!");
        return word;
    }
}
